# you can access in <node ip>:30080
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  ports:
    - port: 8000
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins
  type: NodePort