# secret example with postgres for pass and user
apiVersion: v1
kind: Secret
metadata:
  namespace: postgres
  name: postgres-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=