- name: Provisionar homelab remotamente via ssh
  hosts: homelabs
  become: yes
  tasks:
    - name: Copiar arquivos do repositório atual para o diretório home do host remoto
      synchronize:
        src: "{{ playbook_dir }}/"
        dest: "~/"
        recursive: yes
        mode: push

    - name: Adicionar permissão de execução ao script start.sh
      file:
        path: "~/start.sh"
        mode: 'u+x'

    - name: Executar o script start.sh
      command: "~/start.sh"
